### ISSUE TITLE
 캐릭터 별 베이스 스탯 구현 완료에 따른 이전 todo 마무리 

### ISSUE THREAD

**Issue by Jeon-YJ1004** [SUST22Unity/HumanSurvival#185]
- [x] InGame 씬의 OptionUI에  캐릭터 스탯 연결
- [x] CharacterSelect 씬의 캐릭터 스탯, 이미지 연결
- [x] 강화한 스탯과 기본 스탯 연결

**Comment by seong0929** [comment]
오성혁: CharacterSelect, MapSelect 씬의 캐릭터 스탯, 이미지 연결

**Comment by seong0929** [comment]
캐릭터 순서가 지정되어 있나요?
![image](https://user-images.githubusercontent.com/50050003/227714268-95d0823d-e466-472d-9b9f-38547c2fe8cc.png)

**Comment by yhj0329** [comment]
강화스텟과 기본 스텟 연결, optionUI, levelUpUI에 다 표시되도록 세팅 했습니다.
